# Generated by Django 5.2.7 on 2025-10-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale_Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_Event', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount_percentage', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sale_offers',
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='link',
            new_name='image_url',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('offered_products', models.ManyToManyField(blank=True, to='Customers.product')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
