# Generated by Django 5.2.7 on 2025-10-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_sale_offers_rename_link_product_image_url_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sale_Offers',
            new_name='SaleOffers',
        ),
        migrations.AlterModelTable(
            name='saleoffers',
            table='saleoffers',
        ),
    ]
