# Generated by Django 5.2.7 on 2025-10-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_rename_sale_offers_saleoffers_alter_saleoffers_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='offered_products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
